name: Docker CD hello world workflow
run-name: Running Docker CD hello world workflow by ${{ github.actor }}

on:
  workflow_dispatch:
  push:
    branches:
      - "*"
    tags:
      - "v*"
    paths:
      - "hello-world/**"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ vars.HW_IMAGE_NAME }}

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
  packages: write
  attestations: write
  # pull-requests: write # This is required for updating pull-requests with comments

jobs:
  Docker-Push:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: hello-world

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Extract metadata (tags, labels) for Docker
      #   id: meta
      #   uses: docker/metadata-action@v5
      #   with:
      #     images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      #     tags: |
      #       type=semver,pattern={{version}}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: ./hello-world/
          file: ./hello-world/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ github.sha }}.${{ github.run_number }}
          # tags: ${{ steps.meta.outputs.tags }}
          # labels: ${{ steps.meta.outputs.labels }}

      # - name: Generate artifact attestation
      #   uses: actions/attest-build-provenance@v1
      #   with:
      #     subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
      #     subject-digest: ${{ steps.push.outputs.digest }}
      #     push-to-registry: true
