name: Terraform CD Workflow
run-name: Running Terraform CD Workflow by ${{ github.actor }}

on:
  workflow_dispatch:
  push:
    branches:
      - "*"
    paths:
      - "terraform/**"

env:
  AWS_REGION: ${{ vars.AWS_REGION }}

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  Terraform-Apply:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          audience: sts.amazonaws.com
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}

      - name: Terraform Init
        run: terraform init

      # - name: Terraform workspace list
      #   run: terraform workspace list

      # - name: Terraform workspace new environment and select
      #   run: |
      #     terraform workspace select ${{ github.ref_name }} || terraform workspace new ${{ github.ref_name }}
      #     terraform workspace list

      - name: Terraform Apply
        run: |
          terraform apply -no-color -auto-approve -var-file="${{ github.ref_name }}.tfvars"

      - name: Export terraform outputs
        id: tfout
        run: |
          terraform output
